# Use a slim Python image for a smaller footprint
FROM python:3.11
WORKDIR /app

# Copy requirements first for build caching
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
# RUN pip install -r requirements.txt

# Copy the rest of the Python application code
COPY . .

# The Python app runs on port 8000
EXPOSE 8000

# The command to start the application
CMD ["python", "run.py"]
