services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ./ollama/.ollama:/root/.ollama
    networks:
      - app-network
    # runtime: nvidia
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./db/db-storage:/data/db
    networks:
      - app-network

  socket-server:
    image: socket-server:latest
    container_name: socket-server
    ports:
      - 8080:8080
    depends_on:
      - ollama
      - mongo
    # runtime: nvidia
    environment:
      OLLAMA_HOST: ollama
      OLLAMA_PORT: 11434
      OLLAMA_MODEL: gemma3:1b

      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_NAME: cache
      DATABASE_USER: root
      DATABASE_PASSWORD: root

      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      # NVIDIA_VISIBLE_DEVICES: all

    networks:
      - app-network

networks:
  app-network:
    driver: bridge
